export const CREATING_NEW_CONTACT = "CREATING_NEW_CONTACT";
export const CREATED_NEW_CONTACT = "CREATED_NEW_CONTACT";
export const EDITING_CONTACT = "EDITING_CONTACT";
export const EDITED_CONTACT = "EDITED_CONTACT";
export const REORDER_CONTACT_LIST = "REORDER_CONTACT_LIST";
export const CLOSE_MODAL = "CLOSE_MODAL";
